# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  .secret-file: dmFsdWUtMg0KDQo=
  mongo-password: bW9uZ29wYXNzd29yZA==
  mongo-user: bW9uZ291c2Vy
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{".secret-file":"dmFsdWUtMg0KDQo=","mongo-password":"bW9uZ29wYXNzd29yZA==","mongo-user":"bW9uZ291c2Vy"},"kind":"Secret","metadata":{"annotations":{},"name":"dotfile-secret","namespace":"default"}}
  creationTimestamp: "2024-01-18T05:05:09Z"
  name: mongo-secret
  namespace: default
  resourceVersion: "41645"
  uid: 400a22e1-912f-4001-9971-6716461aed5e
type: Opaque
